[build]
  base = "AnimatiWeb Angular/AnimatiWeb"
  command = "ng build --configuration production"
  publish = "dist/animati-web/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
