import { objetoProducto } from '../pages/admin/productos/productos.component';

let Codigo_Producto: any | objetoProducto['Codigo_Producto'];
export const environment = {
  production: false,
  urlHost: 'https://animatiapp.up.railway.app/',
  urlApi: 'https://animatiapp.up.railway.app/api/',
  API_END_POINT: 'https://animatiapp.up.railway.app/api/',

  METHODS: {
    SLASH: '/',
    GET_ALL_PRODUCT: 'producto/lista',
    GET_PRODUCT_BY_ID: `producto/${Codigo_Producto}`,
    GET_ALL_CATEGORY: 'categoria',
    CREATE_NEW_CATEGORY: 'CreateNewCategory',
    CREATE_PRODUCT: 'producto/crear',
    UPDATE_PRODUCT: 'producto/actualizar/',
    DELETE_PRODUCT: 'producto/eliminar/',
    CREATE_PRODUCT_CART: 'carritoProductos/crear',
    CREATE_CART: 'carrito/crear',
    GET_CART_USER: 'carrito/usuario',
    REMOVE_CART: 'DeleteProductFromCartById?ID=',
    LOGIN: 'Login',
    CREATE_CONTACTO: 'contacto',
    USER_TOKEN_LOGIN: 'Login',
    REGISTER: 'RegisterCustomer',
    PLACE_ORDER: 'PlaceOrder',
    GET_ALL_OFFERS: 'GetAllOffers',
    CREATE_NEW_OFFER: 'CreateNewOffer',
    GET_CUSTOMER_BY_ID: 'GetCustomerById?id=',
    UPDATE_PROFILE: 'UpdateProfile',
    GET_ALL_SALE_BY_CUSTOMER_ID: 'GetAllSaleByCustomerId?id=',
    CANCEL_ORDER_BY_SALE_ID: 'cancelOrder?saleId=',
    OPEN_SALE_BY_SALE_ID: 'OpenSaleBySaleId?saleId=',
    USER_PROFILE: 'perfilusuario',
    RECOVERY_PASS: 'passwordRecovery',
    RECOVERY_PASS_EMAIL: 'passwordRecoveryEmail',
    CHANGE_PASS: 'resetPassword',
    GET_PRODUCT_CART_BY_ID: 'carritoProductos/lista/carrito/',
    DELETE_PRODUCT_CART_BY_ID: 'carritoProductos/eliminar/',
    DELETE_ONE_PRODUCT_CART_BY_ID: 'carritoProductos/eliminarUnidad/',
  },
};
